# Numpy 함수

# 하나의 array에 적용 (단항 유니버셜함수)

유니버셜함수 : ndarray안에 있는 데이터의 요소별로 연산을 수행해주는 함수

In [7]:
import numpy as np

ar1 = np.random.randn(5, 3)
print(ar1)

[[ 0.02996247  1.80943933  1.21660986]
 [ 1.87338421  0.58099092 -0.28984319]
 [-0.16998812  0.90185253 -0.58878568]
 [ 0.23603105 -0.15966543 -0.18288046]
 [-1.04192716 -0.21118684 -0.25288798]]


In [8]:
# 각 요소의 절대값
np.abs(ar1)

array([[0.02996247, 1.80943933, 1.21660986],
       [1.87338421, 0.58099092, 0.28984319],
       [0.16998812, 0.90185253, 0.58878568],
       [0.23603105, 0.15966543, 0.18288046],
       [1.04192716, 0.21118684, 0.25288798]])

In [9]:
# 각 요소의 제곱근 계산 ( == ar1 ** 0.5)
np.sqrt(ar1)

<ipython-input-9-bcb70e1b9820>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(ar1)


array([[0.17309671, 1.34515402, 1.10300039],
       [1.36871627, 0.7622276 ,        nan],
       [       nan, 0.94965917,        nan],
       [0.48583027,        nan,        nan],
       [       nan,        nan,        nan]])

In [10]:
# 각 요소의 제곱 계산
np.square(ar1)

array([[8.97749640e-04, 3.27407071e+00, 1.48013956e+00],
       [3.50956841e+00, 3.37550444e-01, 8.40090722e-02],
       [2.88959598e-02, 8.13337992e-01, 3.46668582e-01],
       [5.57106573e-02, 2.54930504e-02, 3.34452626e-02],
       [1.08561220e+00, 4.45998801e-02, 6.39523290e-02]])

In [11]:
# 각 요소를 자연로그, 상용로그, 아래가 2인 로그를 씌운 값 계산
print(np.log(ar1))
print()
print(np.log10(ar1))
print()
print(np.log2(ar1))

[[-3.50780966  0.59301704  0.19606819]
 [ 0.62774654 -0.54302016         nan]
 [        nan -0.10330426         nan]
 [-1.44379191         nan         nan]
 [        nan         nan         nan]]

[[-1.52342238  0.25754403  0.08515133]
 [ 0.27262686 -0.23583066         nan]
 [        nan -0.04486447         nan]
 [-0.62703086         nan         nan]
 [        nan         nan         nan]]

[[-5.0606996   0.85554274  0.2828666 ]
 [ 0.90564681 -0.78341249         nan]
 [        nan -0.14903654         nan]
 [-2.08295143         nan         nan]
 [        nan         nan         nan]]


<ipython-input-11-9ac07f5d57b3>:2: RuntimeWarning: invalid value encountered in log
  print(np.log(ar1))
<ipython-input-11-9ac07f5d57b3>:4: RuntimeWarning: invalid value encountered in log10
  print(np.log10(ar1))
<ipython-input-11-9ac07f5d57b3>:6: RuntimeWarning: invalid value encountered in log2
  print(np.log2(ar1))


In [12]:
# 각 요소의 부호 나타내기 (+ : 1, - : -1, 0 : 0)
np.sign(ar1)

array([[ 1.,  1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  1., -1.],
       [ 1., -1., -1.],
       [-1., -1., -1.]])

In [13]:
# 각 요소의 소수 첫번째 자리에서 올림한 값 계산
np.ceil(ar1)

array([[ 1.,  2.,  2.],
       [ 2.,  1., -0.],
       [-0.,  1., -0.],
       [ 1., -0., -0.],
       [-1., -0., -0.]])

In [14]:
# 각 요소의 소수 첫번째 자리에서 버림한 값 계산
np.floor(ar1)

array([[ 0.,  1.,  1.],
       [ 1.,  0., -1.],
       [-1.,  0., -1.],
       [ 0., -1., -1.],
       [-2., -1., -1.]])

In [15]:
# 각 요소에서 소수 첫번째 자리에서 반올림한 값 계산
np.round(ar1)

array([[ 0.,  2.,  1.],
       [ 2.,  1., -0.],
       [-0.,  1., -1.],
       [ 0., -0., -0.],
       [-1., -0., -0.]])

In [16]:
# 각 요소가 nan인 경우 True, 아닌 경우 False를 반환
np.isnan(ar1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [17]:
# 각 요소가 무한대인 경우 True, 아닌 경우 False를 반환
np.isinf(ar1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [18]:
# 각 요소에 대해 삼각함수 값을 계산하기 (con, cosh, sin, sinh, tan, tanh)
# ~h : 쌍곡선 함수
# 쌍곡선 : 고정된 두 초점으로부터 거리가 일정한 점들에 의해 나타나는 곡선
np.cos(ar1)

array([[ 0.99955116, -0.23638431,  0.34682744],
       [-0.29799152,  0.83591919,  0.95828871],
       [ 0.98558678,  0.62015776,  0.83161566],
       [ 0.97227375,  0.98728053,  0.98332392],
       [ 0.50455733,  0.97778282,  0.96819389]])

# 두 개의 array에 적용 (이항 유니버셜 함수)

In [19]:
ar1

array([[ 0.02996247,  1.80943933,  1.21660986],
       [ 1.87338421,  0.58099092, -0.28984319],
       [-0.16998812,  0.90185253, -0.58878568],
       [ 0.23603105, -0.15966543, -0.18288046],
       [-1.04192716, -0.21118684, -0.25288798]])

In [20]:
ar2 = np.random.randn(5, 3)
ar2

array([[-1.08259303, -1.37559187,  1.4892769 ],
       [-1.64347487,  1.8074015 , -1.05859146],
       [-0.82478944, -0.73270603,  0.11684605],
       [-0.6887572 ,  0.11860172,  0.93926802],
       [ 2.85747806,  0.47496812,  1.4896467 ]])

In [21]:
# 두 개의 array에 대해 동일한 위치 요소끼리
# 연산 값을 계산함수 (add, subtract, multiply, divide)
np.multiply(ar1, ar2)

array([[-0.03243716, -2.48905003,  1.81186897],
       [-3.07885988,  1.05008385,  0.30682552],
       [ 0.1402044 , -0.66079279, -0.06879728],
       [-0.16256809, -0.01893659, -0.17177377],
       [-2.97728399, -0.10030701, -0.37671374]])

In [22]:
# 두 개의 array에 대해 동일한 위치의 요소끼리 비교해서 최대값 or 최소값 계산
#   (maximum, minimum)
np.maximum(ar1, ar2)

array([[ 0.02996247,  1.80943933,  1.4892769 ],
       [ 1.87338421,  1.8074015 , -0.28984319],
       [-0.16998812,  0.90185253,  0.11684605],
       [ 0.23603105,  0.11860172,  0.93926802],
       [ 2.85747806,  0.47496812,  1.4896467 ]])

# 통계 함수

통계 함수를 통해서 array의 합이나 평균 등을 구할 때

추가로 'axis'라는 파라미터에 대한 값을 지정해서

열 또는 행의 합 또는 평균 등을 구할 수 있음 !

In [24]:
# 열 간의 합을 계산
np.sum(ar1, axis=0)

array([ 0.92746246,  2.92143051, -0.09778744])

In [25]:
# 행 간의 합을 계산
np.sum(ar1, axis=1)

array([ 3.05601167,  2.16453194,  0.14307873, -0.10651484, -1.50600197])

In [26]:
# 전체 요소의 평균을 계산
np.mean(ar1)

0.25007370204833823

In [27]:
# 전체 요소의 표준편차, 분산, 최소값, 최대값 (std, var, min, max)
# 표준편차 : 데이터가 평균으로부터 얼마나 흩어있는지를 나타내는 지표
# 분산 : 데이터가 평균으로부터 얼마나 멀리 떨어져있는지를 측정하는 지표
np.std(ar1)

0.8264744002996276

In [28]:
# 전체 요소의 최소값, 최대값이 위치한 인덱스의 위치를 반환 (argmin, argmax)
np.argmin(ar1)

12

In [29]:
# 맨 처음 요소부터 각 요소까지의 누적합 or 누적곱을 계산 (cumsum, cumprod)
np.cumsum(ar1)

array([0.02996247, 1.83940181, 3.05601167, 4.92939588, 5.5103868 ,
       5.22054361, 5.0505555 , 5.95240803, 5.36362234, 5.5996534 ,
       5.43998796, 5.2571075 , 4.21518034, 4.00399351, 3.75110553])

In [30]:
# 사분위수 : 사분위수는 데이터를 4등분 한 것

# 0.25 : 1 사분위수 / 0.5 : 2 사분위수 (중앙값) / 0.75 : 3 사분위수
np.quantile(ar1, [0.25, 0.5, 0.75])

array([-0.23203741, -0.15966543,  0.74142172])

## 기타함수

In [31]:
# 전체 요소에 대해서 오름차순 정렬
np.sort(ar1)

array([[ 0.02996247,  1.21660986,  1.80943933],
       [-0.28984319,  0.58099092,  1.87338421],
       [-0.58878568, -0.16998812,  0.90185253],
       [-0.18288046, -0.15966543,  0.23603105],
       [-1.04192716, -0.25288798, -0.21118684]])

In [32]:
# 열 방향으로 오름차순 정렬
np.sort(ar1, axis=0)

array([[-1.04192716, -0.21118684, -0.58878568],
       [-0.16998812, -0.15966543, -0.28984319],
       [ 0.02996247,  0.58099092, -0.25288798],
       [ 0.23603105,  0.90185253, -0.18288046],
       [ 1.87338421,  1.80943933,  1.21660986]])

In [33]:
# zip 함수
# 각 객체들을 파라미터로 받고, 그 요소들을 tuple의 형태로 반환
numbers = [1, 2, 3]
letters = ['A', 'B', 'C']
for pair in zip(numbers, letters):
    print(pair)

(1, 'A')
(2, 'B')
(3, 'C')
